import { TUuiModuleFormattedExport } from './types';

const commonDelimiter = ' |\n';

function getUnionItems(packageName: string, exportNameArr: string[]) {
    return exportNameArr.map((e) => `'${packageName}:${e}'`).join(commonDelimiter);
}

export function generateDTS(json: Record<string, TUuiModuleFormattedExport>) {
    const accInitial = 'type Autogenerated_TTsDocExportedEntry = ';
    return Object.keys(json).reduce((acc, packageName, index) => {
        const delimiter = index === 0 ? '' : commonDelimiter;
        const exportNameArr = Object.keys(json[packageName]);
        return acc + delimiter + getUnionItems(packageName, exportNameArr);
    }, accInitial) + ';\n';
}
