export const featureClasses = [
    { id: "PPL", name: "Populated place", description: "A city, town, village, or other agglomeration of buildings where people live and work" },
    { id: "PPLA", name: "Seat of a first-order administrative division", description: "Seat of a first-order administrative division (PPLC takes precedence over PPLA)" },
    { id: "PPLA2", name: "Seat of a second-order administrative division" },
    { id: "PPLA3", name: "Seat of a third-order administrative division" },
    { id: "PPLA4", name: "Seat of a fourth-order administrative division" },
    { id: "PPLC", name: "Capital of a political entity" },
    { id: "PPLCH", name: "Historical capital of a political entity", description: "A former capital of a political entity" },
    { id: "PPLF", name: "Farm/village", description: "A populated place where the population is largely engaged in agricultural activities" },
    { id: "PPLG", name: "Seat of government of a political entity" },
    { id: "PPLH", name: "Historical populated place", description: "A populated place that no longer exists" },
    { id: "PPLL", name: "Populated locality", description: "An area similar to a locality but with a small group of dwellings or other buildings" },
    { id: "PPLQ", name: "Abandoned populated place" },
    { id: "PPLR", name: "Religious populated place", description: "A populated place whose population is largely engaged in religious occupations" },
    { id: "PPLS", name: "Populated places", description: "Cities, towns, villages, or other agglomerations of buildings where people live and work" },
    { id: "PPLW", name: "Destroyed populated place", description: "A village, town or city destroyed by a natural disaster, or by war" },
    { id: "PPLX", name: "Section of populated place" },
    { id: "STLMT", name: "Israeli settlement" },
];