import { TApiReferenceJson } from './types/docsGenSharedTypes';

const commonDelimiter = ' |\n';
const dtsTemplate = (content: string) => {
    return `type Autogenerated_TTsDocExportedEntry = ${content};\n`;
};

function getUnionItems(packageName: string, exportNameArr: string[]) {
    return exportNameArr.map((e) => `'${packageName}:${e}'`).join(commonDelimiter);
}

export function generateDTS(json: TApiReferenceJson['publicTypes']) {
    const content = Object.keys(json).reduce((acc, packageName, index) => {
        const delimiter = index === 0 ? '' : commonDelimiter;
        const exportNameArr = Object.keys(json[packageName]);
        return acc + delimiter + getUnionItems(packageName, exportNameArr);
    }, '');
    return dtsTemplate(content);
}
