/**
 * Please don't make any changes in this file - it's experimental.
 * Also, in the future it may be autogenerated.
 *
 * This file is used as an entry point for Webpack only in case when
 * "app" module imports "build" folder of dependencies rather than
 * their Typescript sources. See "build-experimental" script in package.json for details.
 *
 * This mode is still under development and should not be used on production yet.
 */
/**
 * The order of imports is important.
 */
import '@epam/uui-components/build/styles.css';
import '@epam/uui-timeline/build/styles.css';
import '@epam/uui-docs/build/styles.css';
import '@epam/uui/build/styles.css';
import '@epam/uui-editor/build/styles.css';
/**
 * Import only one of the following styles: "epam-promo" or "loveship".
 */
import '@epam/promo/build/styles.css';
/* import '@epam/loveship/build/styles.css'; */
import './index.tsx';
