import { TCompareStatsResult } from './types';

export function formatResultsToMd(result: TCompareStatsResult) {
    const isErr = result.typesNoComment.isIncreased || result.propsNoComment.isIncreased;
    const typesAmount = formatAmountWithDiff(result.typesNoComment.prev, result.typesNoComment.next);
    const propsAmount = formatAmountWithDiff(result.propsNoComment.prev, result.propsNoComment.next);
    const mdGeneratedBy = 'Generated by: generate-components-api';
    const ciStatus = `CI Status: ${isErr ? 'error' : 'ok'}`;
    const SUMMARY_TITLE = 'New missing comments';
    const SUMMARY_DESC = 'NOTE: Comments in the entities below are missed in the report generated from merge commit, but they aren\'t missed in the target branch report.';
    let detailsMd = '';
    if (isErr) {
        detailsMd = [
            '<details>',
            `<summary>${SUMMARY_TITLE}</summary>`,
            '<br>',
            SUMMARY_DESC,
            '',
            '```',
            newWithNoCommentsToMdList('Types', result.typesNoComment.newWithNoComment),
            newWithNoCommentsToMdList('Props', result.propsNoComment.newWithNoComment),
            '```',
            '</details>',
        ].join('\n');
    }
    return [
        [
            `${mdGeneratedBy}<br>`,
            `${ciStatus}<br>\n`,
            '**Types/Props without comments**<br>',
        ].join(''),
        '',
        '| Entity  | Amount                    |',
        '|:-------:|:-------------------------:|',
        `|  Types  |       ${typesAmount}      |`,
        `|  Props  |       ${propsAmount}      |`,
        detailsMd,
    ].join('\n');

    function newWithNoCommentsToMdList(label: string, items: string[]) {
        if (items.length > 0) {
            const mdList = items.map((line) => `- ${line}`).join('\n');
            return `${label}:\n${mdList}`;
        }
        return '<empty>';
    }
    function formatAmountWithDiff(prev: number | undefined, next: number) {
        let mdTypesAmountChange = '(no baseline :warning:)';
        if (prev !== undefined) {
            const typesAmountDiff = next - prev;
            let typesAmountSign = '';
            let emodji = ':ok:';
            if (typesAmountDiff < 0) {
                typesAmountSign = '';
            } else if (typesAmountDiff > 0) {
                typesAmountSign = '+';
                emodji = ':no_entry:';
            }
            mdTypesAmountChange = `(${typesAmountSign}${typesAmountDiff}) ${emodji}`;
        }
        return `${next} ${mdTypesAmountChange}`;
    }
}
