import { TTypeRef, TTypeSummary } from './sharedTypes';

export type TDocsGenExportedType = Autogenerated_TDocsGenExportedTypeRef;
export type TDocsGenTypeSummary = Record<TTypeRef, TTypeSummary>;
